name: Running on demand automation API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'     
        required: true
        type: choice
        options:
        - dev
        - staging

jobs:
  lint-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint

  run:
    if: ${{ inputs.environment == 'staging' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Echo
        run: echo 'hello world!'
